### PR TITLE
Added variables to hold the Button Text and a Flag to Disable Button Text Updating

### PR DESCRIPTION
**Pull request by jasondavis**

### CODE REVIEW

**Comment by ryanpcmcquen** [comment]
It looks good! Did you run it through a beautifier? A lot of whitespace changes seems to have been made. Will you rebase and match the original styling (`jslint-happy` with `2` spaces)?

If you use [`js-beautify`](http://jsbeautifier.org/), these are the settings:
screen shot 2017-03-09 at 8 23 28 am

**Comment by tspoke** [comment]
Hi,

I was going to create a PR for i18n and I found this one. Could you merge it ? Thanks

**Comment by ryanpcmcquen** [comment]
Hi @tspoke, it has some issues that need resolving, then it will be merged!

**Comment by ryanpcmcquen** [comment]
Thanks for the PR, I have incorporated your changes in and pushed a new release! Kudos to you!

**Pull request closed without merging**
