### PR TITLE
Add `disabled` attribute to `copyItem`.

### PR DESCRIPTION
**Pull request by berndschimmer**
add copyItem.setAttribute("disabled", true); to prefent flickering on ios devices

### CODE REVIEW

**Comment by ryanpcmcquen** [comment]
What iOS device are you on? Also, should this just be handled in the markup instead?

**Comment by berndschimmer** [comment]
I tested this on a real iphone 7 and on the iphoneSE in the simulator. 
What exactly do you mean with "handled in the markup instead"? With css? Than it would be great if the textarea you create has a id or class.

**Comment by ryanpcmcquen** [comment]
In the HTML, just add the word `disabled` to your item. That's more performant and flexible than adding it with JavaScript.

Does the flickering only happen on `textarea`'s, or other elements as well?

**Comment by berndschimmer** [comment]
I use a div and i don't see that you transfer the disabled value from the original textholder to the textarea you create via js. And that's exactly what causes the flickering. See my screencast: https://www.screencast.com/t/lljl0Ly69 
The first run is without disabled, the second one with.

**Comment by ryanpcmcquen** [comment]
Does the `div` have the `disabled` attribute to begin with (in the HTML)?

**Comment by berndschimmer** [comment]
Makes no difference. It is the textarea which forces ios to open the keyboard when you set the focus in it for a view milliseconds without the disabled attribute.

**Comment by ryanpcmcquen** [comment]
OK, thanks for the PR, I'll get the new release out soon!

**Pull request merged**
